version: '3.42'
services:
  brewday-frontend:
    image: brewday-frontend:latest
    build: ./frontend
    ports:
      - 8080:80
  brewday-backend:
    image: brewday-backend:latest
    build: ./backend
    ports:
      - 3000:8080
